export type BrowserErrorCode =
  | "BROWSER_NOT_RUNNING"
  | "PROFILE_NOT_FOUND"
  | "TARGET_NOT_FOUND"
  | "TARGET_ID_MISMATCH"
  | "SNAPSHOT_NOT_FOUND"
  | "STALE_ELEMENT_REF"
  | "ELEMENT_NOT_FOUND"
  | "ACTION_TIMEOUT"
  | "NAVIGATION_BLOCKED"
  | "ACTION_REQUIRES_CONFIRMATION"
  | "SCREENSHOT_FAILED"
  | "NOT_IMPLEMENTED"
  | "ACTION_FAILED"
  | "NAVIGATION_INVALID_URL"
  | "NAVIGATION_PROTOCOL_BLOCKED"
  | "NAVIGATION_PRIVATE_NETWORK_BLOCKED"
  | "NAVIGATION_HOST_NOT_ALLOWED"
  | "NAVIGATION_REDIRECT_BLOCKED"
  | "ACTION_CONTEXT_UNAVAILABLE"
  | "ACTION_TARGET_NOT_FOUND"
  | "ACTION_STALE_SNAPSHOT"
  | "ACTION_DENIED"
  | "CONFIRMATION_NOT_FOUND"
  | "CONFIRMATION_EXPIRED"
  | "CONFIRMATION_STALE"
  | "CONFIRMATION_ALREADY_USED"
  | "CONFIRMATION_MISMATCH";

export class BrowserError extends Error {
  constructor(
    public readonly code: BrowserErrorCode,
    message: string,
    public readonly retryable: boolean = false
  ) {
    super(message);
    this.name = "BrowserError";
  }
}
